services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app/app  # Mount app folder to /app/app in container
    environment:
      - FLASK_ENV=development
      - FLASK_APP=run.py